name: CI
on: [push, pull_request]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.x
      uses: actions/setup-python@v1 # Use pip to install latest FORD
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install ford

    - name: Build documentation
      run: ford ./utf8-f.md

    - name: Deploy Documentation
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs  # The folder the action should deploy.
